### PR TITLE
Rewrite generate_uuid command

### PR DESCRIPTION
**Pull request by poke**
Hey,

I was in need to create only a single UUID and place it into multiple cursors at once, so I added that functionality. While I was doing that, I also cleaned up a few things, and improved the code reuse.

### CODE REVIEW

**Comment by jsadeli** [comment]
Thanks, merged to `master`.

**Comment by poke** [comment]
That was fast, thanks a lot! :)

**Comment by jsadeli** [comment]
still monitoring the project, it's just that there are no new features i
can think of. :)

**Comment by poke** [comment]
Yeah, there isn’t much one can add to UUID generating ;) But thanks for keeping an eye on it!

**Pull request merged**
